#ifndef __CELL_H
#define __CELL_H


#pragma comment(lib, "sysutil_remoteplay_stub")
#pragma comment(lib, "sysutil_savedata_stub")
#pragma comment(lib, "sysutil_screenshot_stub")
#pragma comment(lib, "sysutil_search_stub")
#pragma comment(lib, "sysutil_stub")
#pragma comment(lib, "sysutil_subdisplay_stub")
#pragma comment(lib, "sysutil_sysconf_ext_stub")
#pragma comment(lib, "sysutil_userinfo_stub")
#pragma comment(lib, "sysutil_video_export_stub")
#pragma comment(lib, "sysutil_video_upload_stub")
#pragma comment(lib, "usbd_stub")
#pragma comment(lib, "usbpspcm_stub")
#pragma comment(lib, "vdec_stub")
#pragma comment(lib, "voice_stub")
#pragma comment(lib, "vpost_stub")
#pragma comment(lib, "adec_stub")
#pragma comment(lib, "atrac3plus_stub")
#pragma comment(lib, "audio_stub")
#pragma comment(lib, "c")
#pragma comment(lib, "c_stub")
#pragma comment(lib, "camera_stub")
#pragma comment(lib, "celp8enc_stub")
#pragma comment(lib, "celpenc_stub")
#pragma comment(lib, "cgb")
#pragma comment(lib, "cgc")
#pragma comment(lib, "control_console_ppu")
#pragma comment(lib, "cs")
#pragma comment(lib, "daisy_stub")
#pragma comment(lib, "dbg")
#pragma comment(lib, "dbg_gcm_method_check")
#pragma comment(lib, "dbg_libio_stub")
#pragma comment(lib, "dbgfont")
#pragma comment(lib, "dbgfont_gcm")
#pragma comment(lib, "dbgrsx")
#pragma comment(lib, "dmux_stub")
#pragma comment(lib, "edgeanim")
#pragma comment(lib, "edgeanim_dbg")
#pragma comment(lib, "edgegeomtool")
#pragma comment(lib, "edgegeomtool_dbg")
#pragma comment(lib, "edgelzma")
#pragma comment(lib, "edgelzma_dbg")
#pragma comment(lib, "edgelzo")
#pragma comment(lib, "edgelzo_dbg")
#pragma comment(lib, "edgepost")
#pragma comment(lib, "edgepost_dbg")
#pragma comment(lib, "edgezlib")
#pragma comment(lib, "edgezlib_dbg")
#pragma comment(lib, "face")
#pragma comment(lib, "fiber_stub")
#pragma comment(lib, "fios")
#pragma comment(lib, "flash")
#pragma comment(lib, "font_stub")
#pragma comment(lib, "fontFT_stub")
#pragma comment(lib, "fontGcm")
#pragma comment(lib, "freetype_stub")
#pragma comment(lib, "freetypeTT_stub")
#pragma comment(lib, "fs_stub")
#pragma comment(lib, "ftp")
#pragma comment(lib, "gcm_cmd")
#pragma comment(lib, "gcm_cmdasm")
#pragma comment(lib, "gcm_cmddbg")
#pragma comment(lib, "gcm_gpad_stub")
#pragma comment(lib, "gcm_pm")
#pragma comment(lib, "gcm_sys_stub")
#pragma comment(lib, "gem_stub")
#pragma comment(lib, "gifdec_stub")
#pragma comment(lib, "head_tracker")
#pragma comment(lib, "http_stub")
#pragma comment(lib, "http_util_stub")
#pragma comment(lib, "io_stub")
#pragma comment(lib, "jpgdec_stub")
#pragma comment(lib, "jpgenc_stub")
#pragma comment(lib, "key2char_stub")
#pragma comment(lib, "l10n_stub")
#pragma comment(lib, "lv2_stub")
#pragma comment(lib, "lv2dbg_stub")
#pragma comment(lib, "m")
#pragma comment(lib, "m_stub")
#pragma comment(lib, "medi_stub")
#pragma comment(lib, "mic_stub")
#pragma comment(lib, "mixer")
#pragma comment(lib, "msmp3dec_ppu")
#pragma comment(lib, "msmp3dec_SPURS")
#pragma comment(lib, "mstreamSPURSAT3")
#pragma comment(lib, "mstreamSPURSMP3")
#pragma comment(lib, "mstreamThreadAT3")
#pragma comment(lib, "mstreamThreadMP3")
#pragma comment(lib, "mt19937")
#pragma comment(lib, "net_stub")
#pragma comment(lib, "netctl_stub")
#pragma comment(lib, "ovis_stub")
#pragma comment(lib, "padfilter")
#pragma comment(lib, "pamf_stub")
#pragma comment(lib, "perf")
#pragma comment(lib, "pngdec_stub")
#pragma comment(lib, "pngenc_stub")
#pragma comment(lib, "prof_stub")
#pragma comment(lib, "pthread")
#pragma comment(lib, "resc_stub")
#pragma comment(lib, "rsxdebug")
#pragma comment(lib, "rtc_stub")
#pragma comment(lib, "rudp_stub")
#pragma comment(lib, "sail_rec_stub")
#pragma comment(lib, "sail_stub")
#pragma comment(lib, "scream")
#pragma comment(lib, "sheap_stub")
#pragma comment(lib, "snc")
#pragma comment(lib, "snd3")
#pragma comment(lib, "spudll_stub")
#pragma comment(lib, "spurs_jq_stub")
#pragma comment(lib, "spurs_stub")
#pragma comment(lib, "ssl_stub")
#pragma comment(lib, "stdc++")
#pragma comment(lib, "stdc++_stub")
#pragma comment(lib, "sync_stub")
#pragma comment(lib, "sync2_stub")
#pragma comment(lib, "synth2")
#pragma comment(lib, "syscall")
#pragma comment(lib, "sysmodule_stub")
#pragma comment(lib, "sysutil_ap_stub")
#pragma comment(lib, "sysutil_avc2_stub")
#pragma comment(lib, "sysutil_avconf_ext_stub")
#pragma comment(lib, "sysutil_bgdl_stub")
#pragma comment(lib, "sysutil_game_exec_stub")
#pragma comment(lib, "sysutil_game_stub")
#pragma comment(lib, "sysutil_imejp_stub")
#pragma comment(lib, "sysutil_licensearea_stub")
#pragma comment(lib, "sysutil_music_decode_stub")
#pragma comment(lib, "sysutil_music_export_stub")
#pragma comment(lib, "sysutil_music_stub")
#pragma comment(lib, "sysutil_np_clans_stub")
#pragma comment(lib, "sysutil_np_commerce2_stub")
#pragma comment(lib, "sysutil_np_sns_stub")
#pragma comment(lib, "sysutil_np_stub")
#pragma comment(lib, "sysutil_np_trophy_stub")
#pragma comment(lib, "sysutil_np_tus_stub")
#pragma comment(lib, "sysutil_np_util_stub")
#pragma comment(lib, "sysutil_np2_stub")
#pragma comment(lib, "sysutil_oskdialog_ext_stub")
#pragma comment(lib, "sysutil_photo_decode_stub")
#pragma comment(lib, "sysutil_photo_export_stub")
#pragma comment(lib, "sysutil_photo_import_stub")
#pragma comment(lib, "sysutil_photo_stub")
#pragma comment(lib, "sysutil_print_stub")
#pragma comment(lib, "sysutil_rec_stub")


#include <alloca.h>   //C:\usr\local\cell\target\ppu\include\alloca.h
#include <assert.h>   //C:\usr\local\cell\target\ppu\include\assert.h
#include <cell.h>   //C:\usr\local\cell\target\ppu\include\cell.h
#include <complex.h>   //C:\usr\local\cell\target\ppu\include\complex.h
#include <ctype.h>   //C:\usr\local\cell\target\ppu\include\ctype.h
#include <dirent.h>   //C:\usr\local\cell\target\ppu\include\dirent.h
#include <errno.h>   //C:\usr\local\cell\target\ppu\include\errno.h
#include <fastmath.h>   //C:\usr\local\cell\target\ppu\include\fastmath.h
#include <fcntl.h>   //C:\usr\local\cell\target\ppu\include\fcntl.h
#include <fenv.h>   //C:\usr\local\cell\target\ppu\include\fenv.h
#include <float.h>   //C:\usr\local\cell\target\ppu\include\float.h
#include <inttypes.h>   //C:\usr\local\cell\target\ppu\include\inttypes.h
#include <iso646.h>   //C:\usr\local\cell\target\ppu\include\iso646.h
#include <libftp.h>   //C:\usr\local\cell\target\ppu\include\libftp.h
#include <librsxdebug.h>   //C:\usr\local\cell\target\ppu\include\librsxdebug.h
#include <librsxdebug_io.h>   //C:\usr\local\cell\target\ppu\include\librsxdebug_io.h
#include <librsxdebug_loader.h>   //C:\usr\local\cell\target\ppu\include\librsxdebug_loader.h
#include <limits.h>   //C:\usr\local\cell\target\ppu\include\limits.h
#include <locale.h>   //C:\usr\local\cell\target\ppu\include\locale.h
#include <math.h>   //C:\usr\local\cell\target\ppu\include\math.h
#include <mspace.h>   //C:\usr\local\cell\target\ppu\include\mspace.h
#include <mt19937.h>   //C:\usr\local\cell\target\ppu\include\mt19937.h
#include <netdb.h>   //C:\usr\local\cell\target\ppu\include\netdb.h
#include <np.h>   //C:\usr\local\cell\target\ppu\include\np.h
#include <ppu_altivec_internals.h>   //C:\usr\local\cell\target\ppu\include\ppu_altivec_internals.h
#include <ppu_asm_intrinsics.h>   //C:\usr\local\cell\target\ppu\include\ppu_asm_intrinsics.h
#include <pthread.h>   //C:\usr\local\cell\target\ppu\include\pthread.h
#include <pthread_types.h>   //C:\usr\local\cell\target\ppu\include\pthread_types.h
#include <sched.h>   //C:\usr\local\cell\target\ppu\include\sched.h
#include <semaphore.h>   //C:\usr\local\cell\target\ppu\include\semaphore.h
#include <setjmp.h>   //C:\usr\local\cell\target\ppu\include\setjmp.h
#include <spu_printf.h>   //C:\usr\local\cell\target\ppu\include\spu_printf.h
#include <stdarg.h>   //C:\usr\local\cell\target\ppu\include\stdarg.h
#include <stdbool.h>   //C:\usr\local\cell\target\ppu\include\stdbool.h
#include <stddef.h>   //C:\usr\local\cell\target\ppu\include\stddef.h
#include <stdint.h>   //C:\usr\local\cell\target\ppu\include\stdint.h
#include <stdio.h>   //C:\usr\local\cell\target\ppu\include\stdio.h
#include <stdlib.h>   //C:\usr\local\cell\target\ppu\include\stdlib.h
#include <string.h>   //C:\usr\local\cell\target\ppu\include\string.h
#include <string>
#include <tgmath.h>   //C:\usr\local\cell\target\ppu\include\tgmath.h
#include <time.h>   //C:\usr\local\cell\target\ppu\include\time.h
#include <types.h>   //C:\usr\local\cell\target\ppu\include\types.h
#include <unistd.h>   //C:\usr\local\cell\target\ppu\include\unistd.h
#include <utime.h>   //C:\usr\local\cell\target\ppu\include\utime.h
#include <vec_types.h>   //C:\usr\local\cell\target\ppu\include\vec_types.h
#include <vec_types_gcc.h>   //C:\usr\local\cell\target\ppu\include\vec_types_gcc.h
#include <vec_types_snc.h>   //C:\usr\local\cell\target\ppu\include\vec_types_snc.h
#include <wchar.h>   //C:\usr\local\cell\target\ppu\include\wchar.h
#include <wctype.h>   //C:\usr\local\cell\target\ppu\include\wctype.h
#include <xlocinfo.h>   //C:\usr\local\cell\target\ppu\include\xlocinfo.h
#include <xmtx.h>   //C:\usr\local\cell\target\ppu\include\xmtx.h
#include <xstate.h>   //C:\usr\local\cell\target\ppu\include\xstate.h
#include <xstrxfrm.h>   //C:\usr\local\cell\target\ppu\include\xstrxfrm.h
#include <xtinfo.h>   //C:\usr\local\cell\target\ppu\include\xtinfo.h
#include <xtls.h>   //C:\usr\local\cell\target\ppu\include\xtls.h
#include <xwcc.h>   //C:\usr\local\cell\target\ppu\include\xwcc.h
#include <xwchar.h>   //C:\usr\local\cell\target\ppu\include\xwchar.h
#include <xwcstod.h>   //C:\usr\local\cell\target\ppu\include\xwcstod.h
#include <xwcsxfrm.h>   //C:\usr\local\cell\target\ppu\include\xwcsxfrm.h
#include <xwstr.h>   //C:\usr\local\cell\target\ppu\include\xwstr.h
#include <ymath.h>   //C:\usr\local\cell\target\ppu\include\ymath.h
#include <yvals.h>   //C:\usr\local\cell\target\ppu\include\yvals.h
#include <arpa\inet.h>   //C:\usr\local\cell\target\ppu\include\arpa\inet.h
#include <cell\atomic.h>   //C:\usr\local\cell\target\ppu\include\cell\atomic.h
#include <cell\audio.h>   //C:\usr\local\cell\target\ppu\include\cell\audio.h
#include <cell\camera.h>   //C:\usr\local\cell\target\ppu\include\cell\camera.h
#include <cell\cell_fs.h>   //C:\usr\local\cell\target\ppu\include\cell\cell_fs.h
#include <cell\cgb.h>   //C:\usr\local\cell\target\ppu\include\cell\cgb.h
#include <cell\codec.h>   //C:\usr\local\cell\target\ppu\include\cell\codec.h
#include <cell\control_console.h>   //C:\usr\local\cell\target\ppu\include\cell\control_console.h
#include <cell\daisy.h>   //C:\usr\local\cell\target\ppu\include\cell\daisy.h
#include <cell\dbg.h>   //C:\usr\local\cell\target\ppu\include\cell\dbg.h
#include <cell\dbgfont.h>   //C:\usr\local\cell\target\ppu\include\cell\dbgfont.h
#include <cell\dbgrsx.h>   //C:\usr\local\cell\target\ppu\include\cell\dbgrsx.h
#include <cell\dma.h>   //C:\usr\local\cell\target\ppu\include\cell\dma.h
#include <cell\fios.h>   //C:\usr\local\cell\target\ppu\include\cell\fios.h
#include <cell\font.h>   //C:\usr\local\cell\target\ppu\include\cell\font.h
#include <cell\fontFT.h>   //C:\usr\local\cell\target\ppu\include\cell\fontFT.h
#include <cell\fontGcm.h>   //C:\usr\local\cell\target\ppu\include\cell\fontGcm.h
#include <cell\gcm.h>   //C:\usr\local\cell\target\ppu\include\cell\gcm.h
#include <cell\gcm_pm.h>   //C:\usr\local\cell\target\ppu\include\cell\gcm_pm.h
#include <cell\gem.h>   //C:\usr\local\cell\target\ppu\include\cell\gem.h
#include <cell\http.h>   //C:\usr\local\cell\target\ppu\include\cell\http.h
#include <cell\keyboard.h>   //C:\usr\local\cell\target\ppu\include\cell\keyboard.h
#include <cell\l10n.h>   //C:\usr\local\cell\target\ppu\include\cell\l10n.h
#include <cell\libkey2char.h>   //C:\usr\local\cell\target\ppu\include\cell\libkey2char.h
#include <cell\mic.h>   //C:\usr\local\cell\target\ppu\include\cell\mic.h
#include <cell\mixer.h>   //C:\usr\local\cell\target\ppu\include\cell\mixer.h
#include <cell\mouse.h>   //C:\usr\local\cell\target\ppu\include\cell\mouse.h
#include <cell\mstream.h>   //C:\usr\local\cell\target\ppu\include\cell\mstream.h
#include <cell\ovis.h>   //C:\usr\local\cell\target\ppu\include\cell\ovis.h
#include <cell\pad.h>   //C:\usr\local\cell\target\ppu\include\cell\pad.h
#include <cell\padfilter.h>   //C:\usr\local\cell\target\ppu\include\cell\padfilter.h
#include <cell\resc.h>   //C:\usr\local\cell\target\ppu\include\cell\resc.h
#include <cell\rtc.h>   //C:\usr\local\cell\target\ppu\include\cell\rtc.h
#include <cell\rudp.h>   //C:\usr\local\cell\target\ppu\include\cell\rudp.h
#include <cell\sail.h>   //C:\usr\local\cell\target\ppu\include\cell\sail.h
#include <cell\sail_rec.h>   //C:\usr\local\cell\target\ppu\include\cell\sail_rec.h
#include <cell\scream.h>   //C:\usr\local\cell\target\ppu\include\cell\scream.h
#include <cell\sheap.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap.h
#include <cell\snd3.h>   //C:\usr\local\cell\target\ppu\include\cell\snd3.h
#include <cell\spudll.h>   //C:\usr\local\cell\target\ppu\include\cell\spudll.h
#include <cell\ssl.h>   //C:\usr\local\cell\target\ppu\include\cell\ssl.h
#include <cell\swcache.h>   //C:\usr\local\cell\target\ppu\include\cell\swcache.h
#include <cell\sync.h>   //C:\usr\local\cell\target\ppu\include\cell\sync.h
#include <cell\synth2.h>   //C:\usr\local\cell\target\ppu\include\cell\synth2.h
#include <cell\sysmodule.h>   //C:\usr\local\cell\target\ppu\include\cell\sysmodule.h
#include <cell\usbd.h>   //C:\usr\local\cell\target\ppu\include\cell\usbd.h
#include <cell\usbpspcm.h>   //C:\usr\local\cell\target\ppu\include\cell\usbpspcm.h
#include <cell\voice.h>   //C:\usr\local\cell\target\ppu\include\cell\voice.h
#include <cell\voiceTypes.h>   //C:\usr\local\cell\target\ppu\include\cell\voiceTypes.h
#include <cell\vpost.h>   //C:\usr\local\cell\target\ppu\include\cell\vpost.h
#include <cell\codec\ac3_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\ac3_adapter.h
#include <cell\codec\adec.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\adec.h
#include <cell\codec\adec_base.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\adec_base.h
#include <cell\codec\adec_celp.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\adec_celp.h
#include <cell\codec\adec_celp8.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\adec_celp8.h
#include <cell\codec\adec_m4aac.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\adec_m4aac.h
#include <cell\codec\at3_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\at3_adapter.h
#include <cell\codec\atx_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\atx_adapter.h
#include <cell\codec\celp8enc.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\celp8enc.h
#include <cell\codec\celpenc.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\celpenc.h
#include <cell\codec\dmux.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\dmux.h
#include <cell\codec\dmux_pamf.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\dmux_pamf.h
#include <cell\codec\gifdec.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\gifdec.h
#include <cell\codec\jpgdec.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\jpgdec.h
#include <cell\codec\jpgenc.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\jpgenc.h
#include <cell\codec\libatrac3plus.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\libatrac3plus.h
#include <cell\codec\lpcm_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\lpcm_adapter.h
#include <cell\codec\mp3_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\mp3_adapter.h
#include <cell\codec\mpegbc_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\mpegbc_adapter.h
#include <cell\codec\pamf.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\pamf.h
#include <cell\codec\pngcom.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\pngcom.h
#include <cell\codec\pngdec.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\pngdec.h
#include <cell\codec\pngenc.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\pngenc.h
#include <cell\codec\types.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\types.h
#include <cell\codec\vdec.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\vdec.h
#include <cell\codec\vdec_avc.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\vdec_avc.h
#include <cell\codec\vdec_divx.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\vdec_divx.h
#include <cell\codec\vdec_mpeg2.h>   //C:\usr\local\cell\target\ppu\include\cell\codec\vdec_mpeg2.h
#include <cell\console\console.h>   //C:\usr\local\cell\target\ppu\include\cell\console\console.h
#include <cell\console\io\deci3.h>   //C:\usr\local\cell\target\ppu\include\cell\console\io\deci3.h
#include <cell\console\io\network.h>   //C:\usr\local\cell\target\ppu\include\cell\console\io\network.h
#include <cell\console\plugins\performance_data.h>   //C:\usr\local\cell\target\ppu\include\cell\console\plugins\performance_data.h
#include <cell\console\plugins\screen_shot.h>   //C:\usr\local\cell\target\ppu\include\cell\console\plugins\screen_shot.h
#include <cell\console\plugins\variable_tracker.h>   //C:\usr\local\cell\target\ppu\include\cell\console\plugins\variable_tracker.h
#include <cell\daisy\lfqueue2.h>   //C:\usr\local\cell\target\ppu\include\cell\daisy\lfqueue2.h
#include <cell\daisy\sync_pipe_interlock.h>   //C:\usr\local\cell\target\ppu\include\cell\daisy\sync_pipe_interlock.h
#include <cell\dbgrsx\dbgrsx_bundle_state_struct.h>   //C:\usr\local\cell\target\ppu\include\cell\dbgrsx\dbgrsx_bundle_state_struct.h
#include <cell\dbgrsx\dbgrsx_enum.h>   //C:\usr\local\cell\target\ppu\include\cell\dbgrsx\dbgrsx_enum.h
#include <cell\dbgrsx\dbgrsx_error.h>   //C:\usr\local\cell\target\ppu\include\cell\dbgrsx\dbgrsx_error.h
#include <cell\dbgrsx\dbgrsx_struct.h>   //C:\usr\local\cell\target\ppu\include\cell\dbgrsx\dbgrsx_struct.h
#include <cell\fiber\ppuUtilDefine.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\ppuUtilDefine.h
#include <cell\fiber\ppuUtilRuntime.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\ppuUtilRuntime.h
#include <cell\fiber\ppu_context.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\ppu_context.h
#include <cell\fiber\ppu_fiber.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\ppu_fiber.h
#include <cell\fiber\ppu_fiber_trace.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\ppu_fiber_trace.h
#include <cell\fiber\ppu_initialize.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\ppu_initialize.h
#include <cell\fiber\user_scheduler.h>   //C:\usr\local\cell\target\ppu\include\cell\fiber\user_scheduler.h
#include <cell\fios\fios_base.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_base.h
#include <cell\fios\fios_caching.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_caching.h
#include <cell\fios\fios_collections.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_collections.h
#include <cell\fios\fios_common.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_common.h
#include <cell\fios\fios_configuration.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_configuration.h
#include <cell\fios\fios_dearchive.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_dearchive.h
#include <cell\fios\fios_decompressor.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_decompressor.h
#include <cell\fios\fios_emulation.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_emulation.h
#include <cell\fios\fios_filehandle.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_filehandle.h
#include <cell\fios\fios_media.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_media.h
#include <cell\fios\fios_memory.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_memory.h
#include <cell\fios\fios_op.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_op.h
#include <cell\fios\fios_overlay.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_overlay.h
#include <cell\fios\fios_paths.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_paths.h
#include <cell\fios\fios_platform.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_platform.h
#include <cell\fios\fios_platform_imp.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_platform_imp.h
#include <cell\fios\fios_scheduler.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_scheduler.h
#include <cell\fios\fios_time.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_time.h
#include <cell\fios\fios_types.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_types.h
#include <cell\fios\fios_watch.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\fios_watch.h
#include <cell\fios\ps3\ppu\fios_media_ps3ppu.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\ps3\ppu\fios_media_ps3ppu.h
#include <cell\fios\ps3\ppu\fios_platform_imp_ps3ppu.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\ps3\ppu\fios_platform_imp_ps3ppu.h
#include <cell\fios\ps3\ppu\fios_ps3ppu.h>   //C:\usr\local\cell\target\ppu\include\cell\fios\ps3\ppu\fios_ps3ppu.h
#include <cell\font\error.h>   //C:\usr\local\cell\target\ppu\include\cell\font\error.h
#include <cell\font\libfont.h>   //C:\usr\local\cell\target\ppu\include\cell\font\libfont.h
#include <cell\font\libfontFT.h>   //C:\usr\local\cell\target\ppu\include\cell\font\libfontFT.h
#include <cell\font\libfontGcm.h>   //C:\usr\local\cell\target\ppu\include\cell\font\libfontGcm.h
#include <cell\font\ps3fontset.h>   //C:\usr\local\cell\target\ppu\include\cell\font\ps3fontset.h
#include <cell\fs\cell_fs_errno.h>   //C:\usr\local\cell\target\ppu\include\cell\fs\cell_fs_errno.h
#include <cell\fs\cell_fs_file_api.h>   //C:\usr\local\cell\target\ppu\include\cell\fs\cell_fs_file_api.h
#include <cell\gem\libgem.h>   //C:\usr\local\cell\target\ppu\include\cell\gem\libgem.h
#include <cell\hash\libhash.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libhash.h
#include <cell\hash\libmd5.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libmd5.h
#include <cell\hash\libmd5SPURS.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libmd5SPURS.h
#include <cell\hash\libsha1.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha1.h
#include <cell\hash\libsha1SPURS.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha1SPURS.h
#include <cell\hash\libsha224.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha224.h
#include <cell\hash\libsha224SPURS.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha224SPURS.h
#include <cell\hash\libsha256.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha256.h
#include <cell\hash\libsha256SPURS.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha256SPURS.h
#include <cell\hash\libsha384.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha384.h
#include <cell\hash\libsha384SPURS.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha384SPURS.h
#include <cell\hash\libsha512.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha512.h
#include <cell\hash\libsha512SPURS.h>   //C:\usr\local\cell\target\ppu\include\cell\hash\libsha512SPURS.h
#include <cell\http\client.h>   //C:\usr\local\cell\target\ppu\include\cell\http\client.h
#include <cell\http\error.h>   //C:\usr\local\cell\target\ppu\include\cell\http\error.h
#include <cell\http\net_error.h>   //C:\usr\local\cell\target\ppu\include\cell\http\net_error.h
#include <cell\http\util.h>   //C:\usr\local\cell\target\ppu\include\cell\http\util.h
#include <cell\keyboard\error.h>   //C:\usr\local\cell\target\ppu\include\cell\keyboard\error.h
#include <cell\keyboard\kb_codes.h>   //C:\usr\local\cell\target\ppu\include\cell\keyboard\kb_codes.h
#include <cell\keyboard\libkb.h>   //C:\usr\local\cell\target\ppu\include\cell\keyboard\libkb.h
#include <cell\mic\define.h>   //C:\usr\local\cell\target\ppu\include\cell\mic\define.h
#include <cell\mic\error.h>   //C:\usr\local\cell\target\ppu\include\cell\mic\error.h
#include <cell\mic\interface.h>   //C:\usr\local\cell\target\ppu\include\cell\mic\interface.h
#include <cell\mixer\define.h>   //C:\usr\local\cell\target\ppu\include\cell\mixer\define.h
#include <cell\mixer\error.h>   //C:\usr\local\cell\target\ppu\include\cell\mixer\error.h
#include <cell\mouse\error.h>   //C:\usr\local\cell\target\ppu\include\cell\mouse\error.h
#include <cell\mouse\libmouse.h>   //C:\usr\local\cell\target\ppu\include\cell\mouse\libmouse.h
#include <cell\mouse\mouse_codes.h>   //C:\usr\local\cell\target\ppu\include\cell\mouse\mouse_codes.h
#include <cell\ovis\error.h>   //C:\usr\local\cell\target\ppu\include\cell\ovis\error.h
#include <cell\ovis\util.h>   //C:\usr\local\cell\target\ppu\include\cell\ovis\util.h
#include <cell\pad\error.h>   //C:\usr\local\cell\target\ppu\include\cell\pad\error.h
#include <cell\pad\libpad.h>   //C:\usr\local\cell\target\ppu\include\cell\pad\libpad.h
#include <cell\pad\libpad_dbg.h>   //C:\usr\local\cell\target\ppu\include\cell\pad\libpad_dbg.h
#include <cell\pad\pad_codes.h>   //C:\usr\local\cell\target\ppu\include\cell\pad\pad_codes.h
#include <cell\perf\performance.h>   //C:\usr\local\cell\target\ppu\include\cell\perf\performance.h
#include <cell\rtc\error.h>   //C:\usr\local\cell\target\ppu\include\cell\rtc\error.h
#include <cell\rtc\rtcsvc.h>   //C:\usr\local\cell\target\ppu\include\cell\rtc\rtcsvc.h
#include <cell\sail\au_receiver.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\au_receiver.h
#include <cell\sail\avi.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\avi.h
#include <cell\sail\common.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\common.h
#include <cell\sail\common_rec.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\common_rec.h
#include <cell\sail\converter.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\converter.h
#include <cell\sail\descriptor.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\descriptor.h
#include <cell\sail\feeder_audio.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\feeder_audio.h
#include <cell\sail\feeder_video.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\feeder_video.h
#include <cell\sail\graphics_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\graphics_adapter.h
#include <cell\sail\mp4.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\mp4.h
#include <cell\sail\player.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\player.h
#include <cell\sail\profile.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\profile.h
#include <cell\sail\recorder.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\recorder.h
#include <cell\sail\renderer_audio.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\renderer_audio.h
#include <cell\sail\renderer_video.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\renderer_video.h
#include <cell\sail\sound_adapter.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\sound_adapter.h
#include <cell\sail\source.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\source.h
#include <cell\sail\source_check.h>   //C:\usr\local\cell\target\ppu\include\cell\sail\source_check.h
#include <cell\scream\legacy.h>   //C:\usr\local\cell\target\ppu\include\cell\scream\legacy.h
#include <cell\sheap\error.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\error.h
#include <cell\sheap\key_sheap.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap.h
#include <cell\sheap\key_sheap_barrier.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap_barrier.h
#include <cell\sheap\key_sheap_buffer.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap_buffer.h
#include <cell\sheap\key_sheap_mutex.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap_mutex.h
#include <cell\sheap\key_sheap_queue.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap_queue.h
#include <cell\sheap\key_sheap_rwm.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap_rwm.h
#include <cell\sheap\key_sheap_semaphore.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\key_sheap_semaphore.h
#include <cell\sheap\sheap_base.h>   //C:\usr\local\cell\target\ppu\include\cell\sheap\sheap_base.h
#include <cell\ssl\cert.h>   //C:\usr\local\cell\target\ppu\include\cell\ssl\cert.h
#include <cell\ssl\error.h>   //C:\usr\local\cell\target\ppu\include\cell\ssl\error.h
#include <cell\ssl\ssl.h>   //C:\usr\local\cell\target\ppu\include\cell\ssl\ssl.h
#include <cell\sync\barrier.h>   //C:\usr\local\cell\target\ppu\include\cell\sync\barrier.h
#include <cell\sync\error.h>   //C:\usr\local\cell\target\ppu\include\cell\sync\error.h
#include <cell\sync\lfqueue.h>   //C:\usr\local\cell\target\ppu\include\cell\sync\lfqueue.h
#include <cell\sync\mutex.h>   //C:\usr\local\cell\target\ppu\include\cell\sync\mutex.h
#include <cell\sync\queue.h>   //C:\usr\local\cell\target\ppu\include\cell\sync\queue.h
#include <cell\sync\rwm.h>   //C:\usr\local\cell\target\ppu\include\cell\sync\rwm.h
#include <cell\sync2\cond.h>   //C:\usr\local\cell\target\ppu\include\cell\sync2\cond.h
#include <cell\sync2\mutex.h>   //C:\usr\local\cell\target\ppu\include\cell\sync2\mutex.h
#include <cell\sync2\queue.h>   //C:\usr\local\cell\target\ppu\include\cell\sync2\queue.h
#include <cell\sync2\semaphore.h>   //C:\usr\local\cell\target\ppu\include\cell\sync2\semaphore.h
#include <cell\sync2\thread.h>   //C:\usr\local\cell\target\ppu\include\cell\sync2\thread.h
#include <cell\synth2\sd_compat.h>   //C:\usr\local\cell\target\ppu\include\cell\synth2\sd_compat.h
#include <cell\usbd\error.h>   //C:\usr\local\cell\target\ppu\include\cell\usbd\error.h
#include <cell\usbd\libusbd.h>   //C:\usr\local\cell\target\ppu\include\cell\usbd\libusbd.h
#include <cell\usbd\usb.h>   //C:\usr\local\cell\target\ppu\include\cell\usbd\usb.h
#include <edge\anim\edgeanim_ppu.h>   //C:\usr\local\cell\target\ppu\include\edge\anim\edgeanim_ppu.h
#include <edge\lzma\edgelzma_ppu.h>   //C:\usr\local\cell\target\ppu\include\edge\lzma\edgelzma_ppu.h
#include <edge\lzo\edgelzo_ppu.h>   //C:\usr\local\cell\target\ppu\include\edge\lzo\edgelzo_ppu.h
#include <edge\post\edgepost_mlaa_handler_ppu.h>   //C:\usr\local\cell\target\ppu\include\edge\post\edgepost_mlaa_handler_ppu.h
#include <edge\post\edgePost_ppu.h>   //C:\usr\local\cell\target\ppu\include\edge\post\edgePost_ppu.h
#include <edge\zlib\edgezlib_ppu.h>   //C:\usr\local\cell\target\ppu\include\edge\zlib\edgezlib_ppu.h
#include <flash\atom.h>   //C:\usr\local\cell\target\ppu\include\flash\atom.h
#include <flash\bytearray.h>   //C:\usr\local\cell\target\ppu\include\flash\bytearray.h
#include <flash\error.h>   //C:\usr\local\cell\target\ppu\include\flash\error.h
#include <flash\flash9.h>   //C:\usr\local\cell\target\ppu\include\flash\flash9.h
#include <flash\variant_helper.h>   //C:\usr\local\cell\target\ppu\include\flash\variant_helper.h
#include <GLES\egl.h>   //C:\usr\local\cell\target\ppu\include\GLES\egl.h
#include <GLES\gl.h>   //C:\usr\local\cell\target\ppu\include\GLES\gl.h
#include <GLES\glext.h>   //C:\usr\local\cell\target\ppu\include\GLES\glext.h
#include <net\if_dl.h>   //C:\usr\local\cell\target\ppu\include\net\if_dl.h
#include <net\if_types.h>   //C:\usr\local\cell\target\ppu\include\net\if_types.h
#include <netex\errno.h>   //C:\usr\local\cell\target\ppu\include\netex\errno.h
#include <netex\ifctl.h>   //C:\usr\local\cell\target\ppu\include\netex\ifctl.h
#include <netex\libnetctl.h>   //C:\usr\local\cell\target\ppu\include\netex\libnetctl.h
#include <netex\net.h>   //C:\usr\local\cell\target\ppu\include\netex\net.h
#include <netex\ns.h>   //C:\usr\local\cell\target\ppu\include\netex\ns.h
#include <netex\sockinfo.h>   //C:\usr\local\cell\target\ppu\include\netex\sockinfo.h
#include <netex\udpp2p.h>   //C:\usr\local\cell\target\ppu\include\netex\udpp2p.h
#include <netinet\icmp.h>   //C:\usr\local\cell\target\ppu\include\netinet\icmp.h
#include <netinet\in.h>   //C:\usr\local\cell\target\ppu\include\netinet\in.h
#include <netinet\ip.h>   //C:\usr\local\cell\target\ppu\include\netinet\ip.h
#include <netinet\tcp.h>   //C:\usr\local\cell\target\ppu\include\netinet\tcp.h
#include <np\basic.h>   //C:\usr\local\cell\target\ppu\include\np\basic.h
#include <np\clans.h>   //C:\usr\local\cell\target\ppu\include\np\clans.h
#include <np\commerce2.h>   //C:\usr\local\cell\target\ppu\include\np\commerce2.h
#include <np\common.h>   //C:\usr\local\cell\target\ppu\include\np\common.h
#include <np\custom_menu.h>   //C:\usr\local\cell\target\ppu\include\np\custom_menu.h
#include <np\drm.h>   //C:\usr\local\cell\target\ppu\include\np\drm.h
#include <np\drm_inline.h>   //C:\usr\local\cell\target\ppu\include\np\drm_inline.h
#include <np\error.h>   //C:\usr\local\cell\target\ppu\include\np\error.h
#include <np\friendlist.h>   //C:\usr\local\cell\target\ppu\include\np\friendlist.h
#include <np\lookup.h>   //C:\usr\local\cell\target\ppu\include\np\lookup.h
#include <np\manager.h>   //C:\usr\local\cell\target\ppu\include\np\manager.h
#include <np\matching2.h>   //C:\usr\local\cell\target\ppu\include\np\matching2.h
#include <np\profile.h>   //C:\usr\local\cell\target\ppu\include\np\profile.h
#include <np\ranking.h>   //C:\usr\local\cell\target\ppu\include\np\ranking.h
#include <np\signaling.h>   //C:\usr\local\cell\target\ppu\include\np\signaling.h
#include <np\sns.h>   //C:\usr\local\cell\target\ppu\include\np\sns.h
#include <np\ticket.h>   //C:\usr\local\cell\target\ppu\include\np\ticket.h
#include <np\trophy.h>   //C:\usr\local\cell\target\ppu\include\np\trophy.h
#include <np\tustorage.h>   //C:\usr\local\cell\target\ppu\include\np\tustorage.h
#include <np\util.h>   //C:\usr\local\cell\target\ppu\include\np\util.h
#include <PSGL\deprecated.h>   //C:\usr\local\cell\target\ppu\include\PSGL\deprecated.h
#include <PSGL\export.h>   //C:\usr\local\cell\target\ppu\include\PSGL\export.h
#include <PSGL\psgl.h>   //C:\usr\local\cell\target\ppu\include\PSGL\psgl.h
#include <PSGL\psglu.h>   //C:\usr\local\cell\target\ppu\include\PSGL\psglu.h
#include <PSGL\report.h>   //C:\usr\local\cell\target\ppu\include\PSGL\report.h
#include <sys\ansi.h>   //C:\usr\local\cell\target\ppu\include\sys\ansi.h
#include <sys\cdefs.h>   //C:\usr\local\cell\target\ppu\include\sys\cdefs.h
#include <sys\console.h>   //C:\usr\local\cell\target\ppu\include\sys\console.h
#include <sys\dbg.h>   //C:\usr\local\cell\target\ppu\include\sys\dbg.h
#include <sys\deci3.h>   //C:\usr\local\cell\target\ppu\include\sys\deci3.h
#include <sys\event.h>   //C:\usr\local\cell\target\ppu\include\sys\event.h
#include <sys\exportcplusplus.h>   //C:\usr\local\cell\target\ppu\include\sys\exportcplusplus.h
#include <sys\fixed_addr.h>   //C:\usr\local\cell\target\ppu\include\sys\fixed_addr.h
#include <sys\fs.h>   //C:\usr\local\cell\target\ppu\include\sys\fs.h
#include <sys\fsw.h>   //C:\usr\local\cell\target\ppu\include\sys\fsw.h
#include <sys\fs_external.h>   //C:\usr\local\cell\target\ppu\include\sys\fs_external.h
#include <sys\gpio.h>   //C:\usr\local\cell\target\ppu\include\sys\gpio.h
#include <sys\integertypes.h>   //C:\usr\local\cell\target\ppu\include\sys\integertypes.h
#include <sys\interrupt.h>   //C:\usr\local\cell\target\ppu\include\sys\interrupt.h
#include <sys\memory.h>   //C:\usr\local\cell\target\ppu\include\sys\memory.h
#include <sys\mempool.h>   //C:\usr\local\cell\target\ppu\include\sys\mempool.h
#include <sys\moduleexport.h>   //C:\usr\local\cell\target\ppu\include\sys\moduleexport.h
#include <sys\mself_header.h>   //C:\usr\local\cell\target\ppu\include\sys\mself_header.h
#include <sys\overlay.h>   //C:\usr\local\cell\target\ppu\include\sys\overlay.h
#include <sys\paths.h>   //C:\usr\local\cell\target\ppu\include\sys\paths.h
#include <sys\poll.h>   //C:\usr\local\cell\target\ppu\include\sys\poll.h
#include <sys\ppu_thread.h>   //C:\usr\local\cell\target\ppu\include\sys\ppu_thread.h
#include <sys\process.h>   //C:\usr\local\cell\target\ppu\include\sys\process.h
#include <sys\prx.h>   //C:\usr\local\cell\target\ppu\include\sys\prx.h
#include <sys\prx_error.h>   //C:\usr\local\cell\target\ppu\include\sys\prx_error.h
#include <sys\random_number.h>   //C:\usr\local\cell\target\ppu\include\sys\random_number.h
#include <sys\raw_spu.h>   //C:\usr\local\cell\target\ppu\include\sys\raw_spu.h
#include <sys\return_code.h>   //C:\usr\local\cell\target\ppu\include\sys\return_code.h
#include <sys\select.h>   //C:\usr\local\cell\target\ppu\include\sys\select.h
#include <sys\socket.h>   //C:\usr\local\cell\target\ppu\include\sys\socket.h
#include <sys\spinlock.h>   //C:\usr\local\cell\target\ppu\include\sys\spinlock.h
#include <sys\spu_image.h>   //C:\usr\local\cell\target\ppu\include\sys\spu_image.h
#include <sys\spu_initialize.h>   //C:\usr\local\cell\target\ppu\include\sys\spu_initialize.h
#include <sys\spu_thread.h>   //C:\usr\local\cell\target\ppu\include\sys\spu_thread.h
#include <sys\spu_thread_group.h>   //C:\usr\local\cell\target\ppu\include\sys\spu_thread_group.h
#include <sys\spu_utility.h>   //C:\usr\local\cell\target\ppu\include\sys\spu_utility.h
#include <sys\ss_get_open_psid.h>   //C:\usr\local\cell\target\ppu\include\sys\ss_get_open_psid.h
#include <sys\stat.h>   //C:\usr\local\cell\target\ppu\include\sys\stat.h
#include <sys\synchronization.h>   //C:\usr\local\cell\target\ppu\include\sys\synchronization.h
#include <sys\syscall.h>   //C:\usr\local\cell\target\ppu\include\sys\syscall.h
#include <sys\system_types.h>   //C:\usr\local\cell\target\ppu\include\sys\system_types.h
#include <sys\sys_time.h>   //C:\usr\local\cell\target\ppu\include\sys\sys_time.h
#include <sys\time.h>   //C:\usr\local\cell\target\ppu\include\sys\time.h
#include <sys\timer.h>   //C:\usr\local\cell\target\ppu\include\sys\timer.h
#include <sys\time_util.h>   //C:\usr\local\cell\target\ppu\include\sys\time_util.h
#include <sys\tty.h>   //C:\usr\local\cell\target\ppu\include\sys\tty.h
#include <sys\types.h>   //C:\usr\local\cell\target\ppu\include\sys\types.h
#include <sys\vm.h>   //C:\usr\local\cell\target\ppu\include\sys\vm.h
#include <sysutil\sysutil_ap.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_ap.h
#include <sysutil\sysutil_avc2.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_avc2.h
#include <sysutil\sysutil_avc2_video.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_avc2_video.h
#include <sysutil\sysutil_bgdl.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_bgdl.h
#include <sysutil\sysutil_bgmplayback.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_bgmplayback.h
#include <sysutil\sysutil_common.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_common.h
#include <sysutil\sysutil_gamecontent.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_gamecontent.h
#include <sysutil\sysutil_gameupdate.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_gameupdate.h
#include <sysutil\sysutil_game_common.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_game_common.h
#include <sysutil\sysutil_game_exec.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_game_exec.h
#include <sysutil\sysutil_imejp.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_imejp.h
#include <sysutil\sysutil_licensearea.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_licensearea.h
#include <sysutil\sysutil_msgdialog.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_msgdialog.h
#include <sysutil\sysutil_music.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_music.h
#include <sysutil\sysutil_music2.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_music2.h
#include <sysutil\sysutil_music_decode.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_music_decode.h
#include <sysutil\sysutil_music_decode2.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_music_decode2.h
#include <sysutil\sysutil_music_export.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_music_export.h
#include <sysutil\sysutil_music_playback_common.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_music_playback_common.h
#include <sysutil\sysutil_oskdialog.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_oskdialog.h
#include <sysutil\sysutil_oskdialog_ext.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_oskdialog_ext.h
#include <sysutil\sysutil_photo_decode.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_photo_decode.h
#include <sysutil\sysutil_photo_export.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_photo_export.h
#include <sysutil\sysutil_photo_import.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_photo_import.h
#include <sysutil\sysutil_print.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_print.h
#include <sysutil\sysutil_rec.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_rec.h
#include <sysutil\sysutil_remoteplay.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_remoteplay.h
#include <sysutil\sysutil_savedata.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_savedata.h
#include <sysutil\sysutil_screenshot.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_screenshot.h
#include <sysutil\sysutil_search.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_search.h
#include <sysutil\sysutil_search_types.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_search_types.h
#include <sysutil\sysutil_storagedata.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_storagedata.h
#include <sysutil\sysutil_subdisplay.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_subdisplay.h
#include <sysutil\sysutil_syscache.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_syscache.h
#include <sysutil\sysutil_sysconf.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_sysconf.h
#include <sysutil\sysutil_sysconf_ext.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_sysconf_ext.h
#include <sysutil\sysutil_sysparam.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_sysparam.h
#include <sysutil\sysutil_userinfo.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_userinfo.h
#include <sysutil\sysutil_video_export.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_video_export.h
#include <sysutil\sysutil_video_upload.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_video_upload.h
#include <sysutil\sysutil_webbrowser.h>   //C:\usr\local\cell\target\ppu\include\sysutil\sysutil_webbrowser.h



/*Dumped by Winter*/
#endif